name: 'Build'
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v4

            - name: 'web-ext build'
              id: web-ext-build
              uses: kewisch/action-web-ext@v1
              with:
                  cmd: build
                  filename: '{name}-{version}.xpi'
                  ignoreFiles: '[ "deno.jsonc"]'

            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v4
              with:
                  name: target.xpi
                  path: ${{ steps.web-ext-build.outputs.target }}
